# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\novel_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(824, 593)
        Form.setStyleSheet("Line{background-color:lightgray}")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget_2 = OpacityStackWidget(self.page)
        self.stackedWidget_2.setStyleSheet("border:none")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.list_page = QtWidgets.QWidget()
        self.list_page.setObjectName("list_page")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.list_page)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.listWidget = DragListWidgetEx(self.list_page)
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout_4.addWidget(self.listWidget)
        self.stackedWidget_2.addWidget(self.list_page)
        self.icon_page = QtWidgets.QWidget()
        self.icon_page.setObjectName("icon_page")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.icon_page)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.listWidget_2 = IconsListWidget(self.icon_page)
        self.listWidget_2.setObjectName("listWidget_2")
        self.horizontalLayout_5.addWidget(self.listWidget_2)
        self.stackedWidget_2.addWidget(self.icon_page)
        self.subs_page = QtWidgets.QWidget()
        self.subs_page.setObjectName("subs_page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.subs_page)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.listWidget_3 = SubscribeListWidget(self.subs_page)
        self.listWidget_3.setObjectName("listWidget_3")
        self.verticalLayout_4.addWidget(self.listWidget_3)
        self.stackedWidget_2.addWidget(self.subs_page)
        self.verticalLayout_2.addWidget(self.stackedWidget_2)
        self.frame_2 = QtWidgets.QFrame(self.page)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox = QtWidgets.QCheckBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.checkBox.setFont(font)
        self.checkBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_2.addWidget(self.checkBox)
        self.subs_pushButton = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.subs_pushButton.setFont(font)
        self.subs_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.subs_pushButton.setStyleSheet("QPushButton{border:none}\n"
"QPushButton:checked{border:1px solid lightgray;\n"
"border-radius:2px;background-color: lightgray}\n"
"QPushButton:hover{border:1px solid lightgray;border-radius:2px;background-color:lightgray}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/rss_feeds_72px_1100288_easyicon.net.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.subs_pushButton.setIcon(icon)
        self.subs_pushButton.setCheckable(True)
        self.subs_pushButton.setObjectName("subs_pushButton")
        self.horizontalLayout_2.addWidget(self.subs_pushButton)
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton{border:none}\n"
"QPushButton:checked{border:1px solid lightgray;\n"
"border-radius:2px;background-color: gray}\n"
"QPushButton:hover{border:1px solid lightgray;border-radius:2px;background-color:lightgray}")
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ico/th-list1.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setCheckable(True)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("QPushButton{border:none}\n"
"QPushButton:checked{border:1px solid lightgray;\n"
"border-radius:2px;background-color: gray}\n"
"QPushButton:hover{border:1px solid lightgray;border-radius:2px;background-color:lightgray}")
        self.pushButton_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/ico/th-large1.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setCheckable(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.down_pushButton = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.down_pushButton.setFont(font)
        self.down_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.down_pushButton.setStyleSheet("QPushButton{border: 1px solid #A7BECB; border-radius:5px;\n"
"width: 120%;height: auto; background-color:#F5FBFE}\n"
"QPushButton:hover{border: 1px solid #1996DD; border-radius:5px;color:white; width: 120%;height: auto; background-color:#4AB0EA}")
        self.down_pushButton.setObjectName("down_pushButton")
        self.horizontalLayout_2.addWidget(self.down_pushButton)
        self.count_label = QtWidgets.QLabel(self.frame_2)
        self.count_label.setStyleSheet("color: transparent")
        self.count_label.setObjectName("count_label")
        self.horizontalLayout_2.addWidget(self.count_label)
        spacerItem = QtWidgets.QSpacerItem(190, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.fresh_frame = QtWidgets.QFrame(self.frame_2)
        self.fresh_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fresh_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fresh_frame.setObjectName("fresh_frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.fresh_frame)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.fresh_button = GifButton(self.fresh_frame)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.fresh_button.setFont(font)
        self.fresh_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.fresh_button.setStyleSheet("QPushButton{border:none}\n"
"QPushButton:checked{border:1px solid lightgray;\n"
"border-radius:2px;background-color: gray}\n"
"QPushButton:hover{border:1px solid lightgray;border-radius:2px;background-color:lightgray}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/ico/refresh_173px_1188146_easyicon.net.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fresh_button.setIcon(icon3)
        self.fresh_button.setObjectName("fresh_button")
        self.horizontalLayout_7.addWidget(self.fresh_button)
        self.horizontalLayout_2.addWidget(self.fresh_frame)
        self.filter_frame = QtWidgets.QFrame(self.frame_2)
        self.filter_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.filter_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.filter_frame.setObjectName("filter_frame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.filter_frame)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.comboBox = QtWidgets.QComboBox(self.filter_frame)
        self.comboBox.setStyleSheet("QComboBox {\n"
"    font-family: \"Microsoft YaHei\";\n"
"    background-color:#F5FBFE;\n"
"    color: #000000;\n"
"    padding-left: 5px;\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: lightgray;\n"
"    border-radius:5px\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: center right;\n"
"    width:30px;\n"
"    height:36px;\n"
"    border-left: none;\n"
"}\n"
"QComboBox::down-arrow{\n"
"    width:  30px;\n"
"    height: 30px;\n"
"    image: url(\':/ico/arrow_drop_down.svg\')\n"
"}\n"
"QComboBox:on{ // 激活状态\n"
"    color: red;\n"
"    background-color: lightgray;\n"
"}\n"
"QComboBox:editable {\n"
"    color: white;\n"
"    background-color: #2E3648;\n"
"}\n"
"QComboBox QAbstractItemView::item:selected  \n"
"{     \n"
"    background-color: red;  \n"
"} \n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_8.addWidget(self.comboBox)
        self.filter_button = SiteButton(self.filter_frame)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.filter_button.setFont(font)
        self.filter_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.filter_button.setStyleSheet("QPushButton{border: 1px solid #A7BECB; border-radius:5px;\n"
"width: 110%;height: auto; background-color:#F5FBFE}\n"
"QPushButton:hover{border: 1px solid #C7C7E2; border-radius:5px;color:white; width: 120%;height: auto; background-color:rgb(170, 170, 255)}")
        self.filter_button.setObjectName("filter_button")
        self.horizontalLayout_8.addWidget(self.filter_button)
        self.horizontalLayout_2.addWidget(self.filter_frame)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.page)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setStyleSheet("text-decoration:underline")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.fold_pushButton = QtWidgets.QPushButton(self.frame_3)
        self.fold_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.fold_pushButton.setStyleSheet("QPushButton{border:none}\n"
"QPushButton:hover{border:1px solid lightgray;border-radius:2px;background-color:lightgray}")
        self.fold_pushButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/ico/ellipsis-h.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fold_pushButton.setIcon(icon4)
        self.fold_pushButton.setObjectName("fold_pushButton")
        self.horizontalLayout_3.addWidget(self.fold_pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.stackedWidget.addWidget(self.page)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.page_3)
        self.label_4.setStyleSheet("font: bold 13pt;\n"
"")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.message_label = QtWidgets.QLabel(self.page_3)
        self.message_label.setStyleSheet("font:bold 11pt")
        self.message_label.setText("")
        self.message_label.setAlignment(QtCore.Qt.AlignCenter)
        self.message_label.setWordWrap(True)
        self.message_label.setObjectName("message_label")
        self.verticalLayout_3.addWidget(self.message_label)
        spacerItem2 = QtWidgets.QSpacerItem(20, 109, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.search_label = QtWidgets.QLabel(self.page_3)
        self.search_label.setAlignment(QtCore.Qt.AlignCenter)
        self.search_label.setObjectName("search_label")
        self.verticalLayout_3.addWidget(self.search_label)
        spacerItem3 = QtWidgets.QSpacerItem(20, 108, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.label = QtWidgets.QLabel(self.page_4)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_6 = QtWidgets.QLabel(self.page_4)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.frame_4 = QtWidgets.QFrame(self.page_4)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        self.label_5.setStyleSheet(":hover{color: rgb(169, 199, 255)}")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.verticalLayout.addWidget(self.frame_4)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        self.stackedWidget.addWidget(self.page_4)
        self.gridLayout.addWidget(self.stackedWidget, 1, 0, 1, 1)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.site_button = SiteButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.site_button.setFont(font)
        self.site_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.site_button.setStyleSheet("QPushButton{border: 1px solid #A7BECB; border-radius:5px;\n"
"width: 120%;height: auto; background-color:#F5FBFE}\n"
"QPushButton:hover{border: 1px solid #C7C7E2; border-radius:5px;color:white; width: 120%;height: auto; background-color:#8080C0}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/ico/arrow_drop_down.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.site_button.setIcon(icon5)
        self.site_button.setObjectName("site_button")
        self.horizontalLayout.addWidget(self.site_button)
        self.comboBox_2 = HistoryComboBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.comboBox_2.setFont(font)
        self.comboBox_2.setEditable(True)
        self.comboBox_2.setMaxVisibleItems(10)
        self.comboBox_2.setMaxCount(10)
        self.comboBox_2.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.comboBox_2.setFrame(True)
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout.addWidget(self.comboBox_2)
        self.clear_pushButton = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.clear_pushButton.setFont(font)
        self.clear_pushButton.setStyleSheet("QPushButton{border: 1px solid #A7BECB; border-radius:5px;\n"
"width: 120%;height: auto; background-color:#F5FBFE}\n"
"QPushButton:hover{border: 1px solid #1996DD; border-radius:5px;color:white; width: 120%;height: auto; background-color:#4AB0EA}")
        self.clear_pushButton.setObjectName("clear_pushButton")
        self.horizontalLayout.addWidget(self.clear_pushButton)
        self.search_pushButton = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.search_pushButton.setFont(font)
        self.search_pushButton.setStyleSheet("QPushButton{border: 1px solid #A7BECB; border-radius:5px;\n"
"width: 120%;height: auto; background-color:#F5FBFE}\n"
"QPushButton:hover{border: 1px solid #1996DD; border-radius:5px;color:white; width: 120%;height: auto; background-color:#4AB0EA}")
        self.search_pushButton.setObjectName("search_pushButton")
        self.horizontalLayout.addWidget(self.search_pushButton)
        self.horizontalLayout.setStretch(1, 20)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.checkBox.setText(_translate("Form", "全选"))
        self.subs_pushButton.setText(_translate("Form", "订阅"))
        self.down_pushButton.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">下载所选项</span></p></body></html>"))
        self.down_pushButton.setText(_translate("Form", "下载"))
        self.count_label.setText(_translate("Form", "已选择: 0"))
        self.fresh_button.setText(_translate("Form", "获取最新章节"))
        self.comboBox.setItemText(0, _translate("Form", "所有项"))
        self.comboBox.setItemText(1, _translate("Form", "已下载"))
        self.comboBox.setItemText(2, _translate("Form", "未下载"))
        self.filter_button.setText(_translate("Form", "过滤搜索结果"))
        self.label_2.setText(_translate("Form", "保存目录:"))
        self.label_3.setText(_translate("Form", "c://dfsdf/"))
        self.label_4.setText(_translate("Form", "TextLabel"))
        self.search_label.setText(_translate("Form", "搜索"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">输入</span></p></body></html>"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">小说名</span><span style=\" font-size:10pt; color:#7d7d7d;\">或者</span><span style=\" font-size:11pt; font-weight:600;\">作者名</span></p></body></html>"))
        self.site_button.setText(_translate("Form", "选择搜索源"))
        self.comboBox_2.setPlaceholderText(_translate("Form", "小说名或者作者名"))
        self.clear_pushButton.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">清空搜索记录</span></p></body></html>"))
        self.clear_pushButton.setText(_translate("Form", "清空"))
        self.search_pushButton.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">开始搜索</span></p></body></html>"))
        self.search_pushButton.setText(_translate("Form", "搜索"))
from .customwidgets import DragListWidgetEx, GifButton, HistoryComboBox, IconsListWidget, OpacityStackWidget, SiteButton, SubscribeListWidget
