# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\search_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(463, 43)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        Form.setFont(font)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        self.novel_name = QtWidgets.QLabel(Form)
        self.novel_name.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.novel_name.setObjectName("novel_name")
        self.horizontalLayout.addWidget(self.novel_name)
        self.novel_size = QtWidgets.QLabel(Form)
        self.novel_size.setObjectName("novel_size")
        self.horizontalLayout.addWidget(self.novel_size)
        self.novel_site = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setUnderline(True)
        self.novel_site.setFont(font)
        self.novel_site.setStyleSheet("text-decoration:underline;")
        self.novel_site.setObjectName("novel_site")
        self.horizontalLayout.addWidget(self.novel_site)
        self.info_pushButton = QtWidgets.QPushButton(Form)
        self.info_pushButton.setStyleSheet("QPushButton{border:none}\n"
"QPushButton:hover{background: lightgray; border-radius:2px}")
        self.info_pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/book_1182605_easyicon.net.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.info_pushButton.setIcon(icon)
        self.info_pushButton.setObjectName("info_pushButton")
        self.horizontalLayout.addWidget(self.info_pushButton)
        self.down_pushButton = GifButton(Form)
        self.down_pushButton.setStyleSheet("QPushButton{border:none}\n"
"QPushButton:hover{background: lightgray; border-radius:2px}")
        self.down_pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ico/download_1229240_easyicon.net.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.down_pushButton.setIcon(icon1)
        self.down_pushButton.setObjectName("down_pushButton")
        self.horizontalLayout.addWidget(self.down_pushButton)
        self.horizontalLayout.setStretch(1, 20)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.novel_name.setText(_translate("Form", "1. 诛仙.txt"))
        self.novel_size.setText(_translate("Form", "3MB"))
        self.novel_site.setText(_translate("Form", "知轩藏书"))
        self.info_pushButton.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">详细</span></p></body></html>"))
        self.down_pushButton.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">下载</span></p></body></html>"))
from .customwidgets import GifButton
from .sources_rc import *
